services:
  - type: web
    name: DreamsMusic
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: MONGO_DB_URI
        value: your_mongodb_uri
      - key: STRING_SESSION
        value: your_string_session
