services:
  - type: web
    name: DreamsMusic
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: MONGO_URI
        value: your_mongo_uri
      - key: OWNER_ID
        value: your_owner_id
      - key: LOG_GROUP_ID
        value: your_log_group_id
      - key: STRING_SESSION
        value: your_optional_string
